server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name: tailwind-jte-template

gg:
  jte:
    templateLocation: src/main/jte
    templateSuffix: .jte
    developmentMode: true



